services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  payment-service:
    image: payment-service:v0
    container_name: payment-service
    ports:
      - "8081:8080"  
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped

  # Order Service (Node/Express)
  order-service:
    image: order-service:v0
    container_name: order-service
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=development
    restart: unless-stopped


  notification-service:
    image: notification-service:v0
    container_name: notification-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev   
    restart: unless-stopped



  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - "27017:27017"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres-payment:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpassword
      POSTGRES_DB: paymentdb
    ports:
      - "5433:5432" # host:container